phraseapp:
  access_token:  
  project_id: d971453e2d2e0003df8a56a2b18191c9
  push:
    sources:
    - file: ./en-US.json
      params:
        locale_id: c6a60a221c65bb42ae197feacf44aaf6
        file_format: simple_json
        update_translations: true
        autotranslate: true
    - file: ./ar-SA.json
      params:
        locale_id: 0ff838cb0ab40fdb763d02c0d7645795
        file_format: simple_json
        update_translations: true
  pull:
    targets:
    - file: ./en-US.json
      params:
        locale_id: c6a60a221c65bb42ae197feacf44aaf6
        file_format: simple_json
        update_translations: true
    - file: ./ar-SA.json
      params:
        locale_id: 0ff838cb0ab40fdb763d02c0d7645795
        file_format: simple_json
        include_unverified_translation: true
        update_translations: true