phraseapp:
  access_token: ec6f12240a3710fda3a019ed557c26eaf32f77d73ce309a29ced34dd10f959be 
  project_id: 3bff7b01dba2bb5fd9257f5198663f13
  push:
    sources:
    - file: ./en-US.json
      params:
        file_format: simple_json
    - file: ./ar-SA.json
      params:
        file_format: simple_json
        update_translations: true
  pull:
    targets:
    - file: ./en-US.json
      params:
        file_format: simple_json
    - file: ./ar-SA.json
      params:
        file_format: simple_json
        include_unverified_translation: true
