phraseapp:
  access_token:  
  project_id: 21e6ec743d5081b063956aa28792b80e
  push:
    sources:
    - file: ./android/en-US/strings.xml
      params:
        locale_id: 6657f846b11c99c32ae2c974bb420049
        file_format: xml
        update_translations: true
        autotranslate: true
  pull:
    targets:
    - file: ./android/ar-SA/strings.xml
      params:
        locale_id: 1ee40135ee356a323ea781c3e771e1e8
        file_format: xml
        include_unverified_translation: true
        update_translations: true